### PR TITLE
Pick up socks proxy from RIEMANN_PROXY variable

### PR DESCRIPTION
**Pull request by ktf**
I was under the need of connecting to a Riemann instance in a cluster which only exposes ssh to the outside, so I ended up adding SOCKS support this way.

### CODE REVIEW

**Comment by amir** [comment]
Hi,

Sorry for being late in responding. Do you think that also having it as a command-line flag would be beneficial to the user? And/or even respecting `http_proxy` and `https_proxy` environment variables?

**Comment by ktf** [comment]
Given Riemann does not use HTTP/HTTPS to communicate I thought having a separate variable would be better. Command line option would be nice.

**Comment by amir** [comment]
Sorry, I'm not sure what I was thinking when I made that comment. What does it even mean to add command line flags to a library?

I had to refactor out the Dialer creation logic into a separate function for the sake of testability, but testing it turned out to be harder than I anticipated so I had to add a horrible hack to be able to test it. I'm sure there's a cleaner way to test it but as far as I can see `golang.org/x/net/proxy` exports nothing. Apologies that the final code that got merged is not as elegant as your original pull request.

**Comment by ktf** [comment]
Ah, right... Of course what should have the command line flag is obiously the utility using this. Indeed the whole thing should be refactored in a way the proxy can be set from the outside.

**Pull request merged**
